### ISSUE TITLE
Playerdatastorage does not write file

### ISSUE THREAD

**Issue by shadow501pl** [Daylily-Zeleen/GD-EOS#3]
When i try to write using playerdatastorage, i always get WriteData callback failed.

Both cache directory and encryption key are set.

code:
func _ready():
	# wait for login
	await Main.logged_in
	# Init
	# Checking for username
	var check_username = await EOSPlayerDataStorage.query_file(Main.local_id, "username.txt")
	var username = ""
	if check_username.result_code == EOS.NotFound:
		# Generate new username
		username = "NewPlayer" + str(randi_range(1111, 9999))
		# Save File
		var file = FileAccess.open(Global.cache_directory + "username.txt",FileAccess.WRITE)
		print(Global.cache_directory + "username.txt")
		file.store_string(username)
		file.close()
		#
		var options = EOSPlayerDataStorage_WriteFileOptions.new()
		options.filename = "username.txt"
		options.chunk_length_bytes = 4096
		options.local_user_id = Main.local_id
		var test = EOSPlayerDataStorage.write_file(options)

Error:
[LogEOSPlayerDataStorage]: WriteData callback failed.
[LogEOSPlayerDataStorage]: Deleting local scratch file as the file was not written to successfully. ScratchFilename=[C:/...emp/datastorage/scratch/e06da7e7775748b1a792fcedf088a3ce/000...b00/username.txt]

**Comment by shadow501pl** [comment]
Nvm, seems like i was using an encryption key 64 characters long and not 64 bytes long

**Comment by shadow501pl** [comment]
Nvm now its crashing, without any error message.

**Comment by Daylily-Zeleen** [comment]
To facilitate others to review your code, you should follow Markdown's code block syntax and mark it as GDScript.

You have not set `write_file_data_callback` for `EOSPlayerDataStorage_WriteFileOptions`, it means that you have not provide ability for writing file for this operation.

I have not time to make document. Please refer source code for more details.

**Comment by shadow501pl** [comment]
It doesn't call, because the game crashes when i call  EOSPlayerDataStorage.write_file(options)

**Comment by Daylily-Zeleen** [comment]
1. Launch your game with "-v" argument to get last call stack before crashing in command line.
2. Provide your MRP.

**Comment by shadow501pl** [comment]
I already swapped over to https://github.com/3ddelano/epic-online-services-godot/

**Comment by Daylily-Zeleen** [comment]
Useless issue, could not reproduce in latest version.
